services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gukesh12garry@
      MYSQL_DATABASE: iris_systems_rec_task_development
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rails_network

  app:
    build: .
    container_name: rails-app
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Gukesh12garry@
      DATABASE_NAME: iris_systems_rec_task_development
    networks:
      - rails_network
    command: bash -lc "bundle _2.6.6_ exec rails s -b 0.0.0.0"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - rails_network

volumes:
  db_data:

networks:
  rails_network:
