services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gukesh12garry@
      MYSQL_DATABASE: iris_systems_rec_task_development
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rails_network

  app1:
    build: .
    container_name: rails-app1
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Gukesh12garry@
      DATABASE_NAME: iris_systems_rec_task_development
    volumes:
      - rails_logs:/app/log
    networks:
      - rails_network
    command: bash -lc "bundle _2.6.6_ exec rails s -b 0.0.0.0"

  app2:
    build: .
    container_name: rails-app2
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Gukesh12garry@
      DATABASE_NAME: iris_systems_rec_task_development
    volumes:
      - rails_logs:/app/log
    networks:
      - rails_network
    command: bash -lc "bundle _2.6.6_ exec rails s -b 0.0.0.0"

  app3:
    build: .
    container_name: rails-app3
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Gukesh12garry@
      DATABASE_NAME: iris_systems_rec_task_development
    volumes:
      - rails_logs:/app/log
    networks:
      - rails_network
    command: bash -lc "bundle _2.6.6_ exec rails s -b 0.0.0.0"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_config:/etc/nginx
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - rails_network
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - rails_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - rails_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - rails_network

volumes:
  db_data:
  nginx_config:
  rails_logs:
  grafana_data:

networks:
  rails_network:
